# Generated by Django 5.2.1 on 2025-05-20 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curtida',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='foto',
            name='data_envio',
        ),
        migrations.AddField(
            model_name='curtida',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('administradores', models.ManyToManyField(related_name='grupos_administrando', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(related_name='grupos_participando', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.grupo'),
        ),
    ]
