# Generated by Django 5.2.1 on 2025-05-20 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_curtida_unique_together_remove_foto_data_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
